REM ### CONFIG DBPROD POSTGIS
REM # CONFIG VARIABLES POSTGRESQL

REM Configurer pgpassword et user. 
REM OPTINONNEL, LES SCRIPTS CONSIDERENT L'UTILISATION D'UN PASSWORD FILE
REM SET PGPASSWORD=
SET PGHOSTNAME=localhost
SET PGPORT=5432
SET PGDB=opentelcos
SET PGUSER=postgres
REM SET PGSCHEMA=gracethd

REM VARIABLE POSTGRESQL POUR FIXER L'ENCODAGE DES SORTIES (PGSQL2SHP). NON TESTE. 
SET pgclientencoding=WIN1252
REM shp2pgsql -s 2154 -a -W cp1252 t_adresse gracethd.t_adresse > t_adresse.sql
REM SET PGSRC=D:\postgres_files\shpcsv-out
SET PGSHPINPATH=D:\postgres_files\shpcsv-in
SET PGSHPOUTPATH=D:\postgres_files\shpcsv-out
SET PGSRID=2154
SET PGCODE=cp1252
SET PGCSVCONF= WITH DELIMITER ';' CSV HEADER ENCODING 'UTF8'
REM GOTO:EOF

SET OTSCRPATH=C:\opentelcos\sql_postgis
